### VARIABLES

@testUserToken = {{$dotenv TEST_USER_TOKEN}}

@testUserId = {{$dotenv TEST_USER_ID}}

@apiKey = {{$dotenv APIKEY}}

### GET /

GET http://localhost:3000/

### GET ALL USERS

GET http://localhost:3000/auth/
apikey: {{apiKey}}

### POST /register (register a new user)

POST http://localhost:3000/auth/register 
Content-Type: application/json
apikey: {{apiKey}}

{
    "name": "Test User",
    "email": "testmail@test.com",
    "username": "testuser",
    "password": "testpassword"
}

### post

POST http://localhost:3000/auth/register 
Content-Type: application/json
apikey: {{apiKey}}

{
    "name": "dd",
    "email": "dddtest.com",
    "username": "ddd",
    "password": "daaaa"
}

### POST /login (login a user)

POST http://localhost:3000/auth/login 
Content-Type: application/json
apikey: {{apiKey}}

{
    "email": "testmail@test.com",
    "password": "testpassword"
}

### POST /login (login with username)

POST http://localhost:3000/auth/login 
Content-Type: application/json
apikey: {{apiKey}}

{
    "username": "testuser",
    "password": "testpassword"
}

### DELETE /delete (delete a user) (protected)

@deletionId = 021bfcb3-34b2-47a7-ae61-ee7cfbc6e162

DELETE http://localhost:3000/auth/delete/{{deletionId}} 
Content-Type: application/json
apikey: {{apiKey}}
Authorization: {{testUserToken}}