### ENVIRONMENT VARIABLES

@apiKey = {{$dotenv APIKEY}}

@testUserToken = {{$dotenv TEST_USER_TOKEN}}

@testUserId = {{$dotenv TEST_USER_ID}}

@url = http://localhost:3000

@url = {{$dotenv DEV_PROD_URL}}

### FILE VARIABLEs

@semesterId = cmb5awkck0001c2xmhwyg126f

### GET /semesters (get all semesters for a user) (protected)

GET {{url}}/semesters 
Content-Type: application/json
apikey: {{apiKey}}
Authorization: {{testUserToken}}

{
    "userId": "{{testUserId}}"
}

### GET /semesters?search="" (get a semester by string) (protected)

@searchString = 25

GET {{url}}/semesters?search={{searchString}} 
Content-Type: application/json
apikey: {{apiKey}}
Authorization: {{testUserToken}}

{
    "userId": "{{testUserId}}"
}

### GET /semesters/:id (get a semester by id with its subjects) (protected)

GET {{url}}/semesters/{{semesterId}} 
Content-Type: application/json
apikey: {{apiKey}}
Authorization: {{testUserToken}}

### POST /semesters (create a new semester) (protected)

POST {{url}}/semesters 
Content-Type: application/json
apikey: {{apiKey}}
Authorization: {{testUserToken}}

{
    "semester": "2024/25",
    "userId": "{{testUserId}}"
}

### PUT /semesters/:id (update a semester) (protected)

@updateId = a61c9245-d562-4250-9f95-12d85a5c8ab1

PUT {{url}}/semesters/{{updateId}} 
Content-Type: application/json
apikey: {{apiKey}}
Authorization: {{testUserToken}}

{
    "semester": "2024/kdkdkdkd",
    "userId": "{{testUserId}}"
}

### DELETE /semesters/:id (delete a semester) (protected)

@deleteId = a61c9245-d562-4250-9f95-12d85a5c8ab1

DELETE {{url}}/semesters/{{deleteId}} 
Content-Type: application/json
apikey: {{apiKey}}
Authorization: {{testUserToken}}

{
    "userId": "{{testUserId}}"
}