### VARIABLES

@apiKey = {{$dotenv APIKEY}}

@testUserToken = {{$dotenv TEST_USER_TOKEN}}

@testUserId = {{$dotenv TEST_USER_ID}}

@semesterId = cmb5awkck0001c2xmhwyg126f

@subjectId = cmb5b7abs0007c2s6ik8v9dlf

@url = http://localhost:3000

@url = {{$dotenv DEV_PROD_URL}}

### GET /subjects (get all subjects) (protected)

GET {{url}}/subjects 
Content-Type: application/json
apikey: {{apiKey}}
Authorization: {{testUserToken}}

{
    "semesterId": "{{semesterId}}"
}

### GET /subjects/:id (get a subject by id) (protected)

@getSubjId = cmb5b7abs0007c2s6ik8v9dlf

GET {{url}}/subjects/{{getSubjId}} 
Content-Type: application/json
apikey: {{apiKey}}
Authorization: {{testUserToken}}

### CREATE /subjects (create a new subject) (protected)

POST {{url}}/subjects 
Content-Type: application/json
apikey: {{apiKey}}
Authorization: {{testUserToken}}

{
    "name": "Informatik",
    "semesterId": "{{semesterId}}"
}

### UPDATE /subjects/:id (update a subject) (protected)

@updateSubjId = cmb5axh2f0003c2xm2klocuw2

PUT {{url}}/subjects/{{updateSubjId}} 
Content-Type: application/json
apikey: {{apiKey}}
Authorization: {{testUserToken}}

{
    "name": "Informatik"
}

### DELETE /subjects/:id (delete a subject) (protected)

@deleteSubjId = cmb5axh2f0003c2xm2klocuw2

DELETE {{url}}/subjects/{{deleteSubjId}} 
Content-Type: application/json
apikey: {{apiKey}}
Authorization: {{testUserToken}}