### VARIABLES

@apiKey = {{$dotenv APIKEY}}

@testUserToken = {{$dotenv TEST_USER_TOKEN}}

@subjectId = cmb5b7abs0007c2s6ik8v9dlf

@url = http://localhost:3000

@url = {{$dotenv DEV_PROD_URL}}

### GET /grades (get all grades for a subject) (protected)

GET {{url}}/grades 
Content-Type: application/json
apikey: {{apiKey}}
Authorization: {{testUserToken}}

{
    "subjectId": "{{subjectId}}"
}

### POST /grades (create a new grade) (protected)

POST {{url}}/grades 
Content-Type: application/json
apikey: {{apiKey}}
Authorization: {{testUserToken}}

{
    "subjectId": "{{subjectId}}",
    "grade": "2.3",
    "type": "Stegreifaufgabe",
    "date": "2025-05-29T16:32:05.265Z"
}

### PUT /grades (update a grade) (protected)

@putGrade = cmb5bb7eo000fc2s6zc16xyad

PUT {{url}}/grades/{{putGrade}} 
Content-Type: application/json
apikey: {{apiKey}}
Authorization: {{testUserToken}}

{
    "type": "Updated Type",
    "grade": "4",
    "date": "2025-05-25T16:32:05.265Z"
}

### DELETE /grades (delete a grade) (protected)

@deleteGrade = cmb5b7o29000bc2s6j5i4ycgw

DELETE {{url}}/grades/{{deleteGrade}} 
Content-Type: application/json
apikey: {{apiKey}}
Authorization: {{testUserToken}}