### VARIABLES

@devtoken = {{$dotenv DEV_TOKEN}}

@devUserId = {{$dotenv DEV_USER_ID}}

@apiKey = {{$dotenv APIKEY}}

### GET /

GET http://localhost:3000/

### GET ALL USERS

GET http://localhost:3000/auth/
apikey: {{apiKey}}

### POST /register (register a new user)

POST http://localhost:3000/auth/register 
Content-Type: application/json
apikey: {{apiKey}}

{
    "name": "New User",
    "email": "testmail@test.com",
    "username": "newuser",
    "password": "newpassword"
}

### post

POST http://localhost:3000/auth/register 
Content-Type: application/json
apikey: {{apiKey}}

{
    "name": "dd",
    "email": "dddtest.com",
    "username": "ddd",
    "password": "daaaa"
}

### POST /login (login a user)

POST http://localhost:3000/auth/login 
Content-Type: application/json
apikey: {{apiKey}}

{
    "email": "testmail@test.com",
    "password": "newpassword"
}

### POST /login (login with username)

POST http://localhost:3000/auth/login 
Content-Type: application/json
apikey: {{apiKey}}

{
    "username": "newuser",
    "password": "newpassword"
}

### DELETE /delete (delete a user) (protected)

@deletionId = cmajp9hg80000tszx5oplpymr

DELETE http://localhost:3000/auth/delete/{{deletionId}} 
Content-Type: application/json
apikey: {{apiKey}}
Authorization: {{devtoken}}