### VARIABLES
@apiKey = {{$dotenv APIKEY}}

@devToken = {{$dotenv DEV_USER_TOKEN}}

@devUserId = {{$dotenv DEV_USER_ID}}

@semesterId = cma5ecgn40003ts691d1lcup2

@subjectId = cma5hmbvw00015bfjfe4i6cwr

### GET /subjects (get all subjects) (protected)

GET http://localhost:3000/subjects 
Content-Type: application/json
apikey: {{apiKey}}
Authorization: {{devToken}}

{
    "semesterId": "{{semesterId}}"
}

### GET /subjects/:id (get a subject by id) (protected)

GET http://localhost:3000/subjects/{{subjectId}} 
Content-Type: application/json
apikey: {{apiKey}}
Authorization: {{devToken}}

### CREATE /subjects (create a new subject) (protected)

POST http://localhost:3000/subjects 
Content-Type: application/json
apikey: {{apiKey}}
Authorization: {{devToken}}

{
    "name": "Test",
    "semesterId": "{{semesterId}}"
}

### UPDATE /subjects/:id (update a subject) (protected)

@updateId = cma6j27310001ts7cxsxh8jxw

PUT http://localhost:3000/subjects/{{updateId}}
Content-Type: application/json
apikey: {{apiKey}}
Authorization: {{devToken}}

{
    "name": "Updated Subject"
}

### DELETE /subjects/:id (delete a subject) (protected)

@deleteId = cma6j27310001ts7cxsxh8jxw

DELETE http://localhost:3000/subjects/{{deleteId}} 
Content-Type: application/json
apikey: {{apiKey}}
Authorization: {{devToken}}