### VARIABLES

@supabaseApikey = {{$dotenv SUPABASE_APIKEY}}
@apiKey = {{$dotenv APIKEY}}

@url = http://localhost:3000

@url = {{$dotenv DEV_PROD_URL}}

### Local Health Check

GET {{url}}/health

### Teapot

GET {{url}}/

### PostgreSQL Instance Health Check

GET https://fqxigjztdwogydtgfvvs.supabase.co/health 
apikey: {{supabaseApikey}}